// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJsMGM6r-lnCglPohvVRSwy9aJui8K6rs',
    appId: '1:1006572169850:web:d3d9e10899e5f5721c29c3',
    messagingSenderId: '1006572169850',
    projectId: 'medicare-connect-d8a0b',
    authDomain: 'medicare-connect-d8a0b.firebaseapp.com',
    storageBucket: 'medicare-connect-d8a0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZ3ic1IsVKlbLIBCg_7oExrKKY13RLUg',
    appId: '1:1006572169850:android:d530f2f5dbdf99b81c29c3',
    messagingSenderId: '1006572169850',
    projectId: 'medicare-connect-d8a0b',
    storageBucket: 'medicare-connect-d8a0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvhKbG861bnbWfJRXpOWsQK-wr0U-yln4',
    appId: '1:1006572169850:ios:0e38d338b55ac6d81c29c3',
    messagingSenderId: '1006572169850',
    projectId: 'medicare-connect-d8a0b',
    storageBucket: 'medicare-connect-d8a0b.firebasestorage.app',
    iosBundleId: 'com.example.medicareConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvhKbG861bnbWfJRXpOWsQK-wr0U-yln4',
    appId: '1:1006572169850:ios:0e38d338b55ac6d81c29c3',
    messagingSenderId: '1006572169850',
    projectId: 'medicare-connect-d8a0b',
    storageBucket: 'medicare-connect-d8a0b.firebasestorage.app',
    iosBundleId: 'com.example.medicareConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJsMGM6r-lnCglPohvVRSwy9aJui8K6rs',
    appId: '1:1006572169850:web:f8076ff20f449d111c29c3',
    messagingSenderId: '1006572169850',
    projectId: 'medicare-connect-d8a0b',
    authDomain: 'medicare-connect-d8a0b.firebaseapp.com',
    storageBucket: 'medicare-connect-d8a0b.firebasestorage.app',
  );
}
